# Generated by Django 4.0.4 on 2022-09-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Italingua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumquestion',
            name='numberOfReplies',
        ),
    ]
