# Generated by Django 4.0.4 on 2022-09-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Italingua', '0002_remove_forumquestion_numberofreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='numberOfReplies',
            field=models.IntegerField(default=0),
        ),
    ]
