# Generated by Django 4.0.4 on 2022-09-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Italingua', '0003_forumquestion_numberofreplies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
