# Generated by Django 4.0.4 on 2022-09-29 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Italingua', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replyTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Italingua.forumquestion'),
        ),
    ]
